on:
  schedule:
    - cron:  '40 2,14 * * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    container: thohan88/covid19-nor-data
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        Rscript -e 'source("code/refresh_files.R")'
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add temp.txt
        git commit -m "Scheduled data update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
